#!/usr/bin/env python3

import argparse
import html
import re
import sys
from pathlib import Path
from typing import Optional


TRAILING_FOOTER = re.compile(
    r"\n{2}<sub>(?:🤖 )?Generated by [^\r\n]*\.</sub>"
    r"(?:\n<!--\s*ai-generation:[^\r\n]*-->)?\s*\Z",
    re.IGNORECASE,
)


def normalize_label(value: Optional[str]) -> Optional[str]:
    if value is None:
        return None

    label = " ".join(value.split()).removesuffix(".")
    return label or None


def read_body(path: Path, parser: argparse.ArgumentParser) -> str:
    try:
        body = path.read_text(encoding="utf-8")
    except (OSError, UnicodeError) as error:
        parser.error(f"Body file is not readable UTF-8: {path}: {error}")

    body = TRAILING_FOOTER.sub("", body.rstrip()).rstrip()
    if not body:
        parser.error("Body file must contain a reply")

    return body


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Append a generation footer to a GitHub review reply."
    )
    parser.add_argument("--body-file", required=True, type=Path)
    parser.add_argument(
        "--session-info",
        help="Display-ready model information exposed by the current session or turn.",
    )
    parser.add_argument(
        "--user-provided-info",
        help="Display-ready model information supplied by the user.",
    )
    args = parser.parse_args()

    body = read_body(args.body_file, parser)
    session_info = normalize_label(args.session_info)
    user_provided_info = normalize_label(args.user_provided_info)

    if session_info:
        model_information = session_info
    elif user_provided_info:
        model_information = f"{user_provided_info} (user-provided)"
    else:
        model_information = "Codex"

    safe_information = html.escape(model_information, quote=False)
    footer = f"<sub>🤖 Generated by {safe_information}.</sub>"
    sys.stdout.write(f"{body}\n\n{footer}\n")


if __name__ == "__main__":
    main()
