#!/usr/bin/env bash
set -euo pipefail

usage() {
  echo "Usage: $(basename "$0") --body-file <path> --model-id <id> --control <name> --value <value>" >&2
  exit 2
}

body_file=""
model_id=""
control=""
value=""

while (($#)); do
  case "$1" in
    --body-file|--model-id|--control|--value)
      (($# >= 2)) || usage
      case "$1" in
        --body-file) body_file="$2" ;;
        --model-id) model_id="$2" ;;
        --control) control="$2" ;;
        --value) value="$2" ;;
      esac
      shift 2
      ;;
    *) usage ;;
  esac
done

[[ -n "$body_file" && -n "$model_id" && -n "$control" && -n "$value" ]] || usage
[[ -f "$body_file" && -r "$body_file" ]] || { echo "Body file is not readable: $body_file" >&2; exit 2; }
[[ -s "$body_file" ]] || { echo "Body file must not be empty" >&2; exit 2; }

metadata_pattern='^[A-Za-z0-9][A-Za-z0-9._:/+-]*$'
[[ "$model_id" =~ $metadata_pattern ]] || { echo "Model ID contains unsupported characters" >&2; exit 2; }
[[ "$control" =~ $metadata_pattern ]] || { echo "Control contains unsupported characters" >&2; exit 2; }
[[ "$value" =~ $metadata_pattern ]] || { echo "Value contains unsupported characters" >&2; exit 2; }

if grep -Eqi '(<sub>[[:space:]]*Generated by|<!--[[:space:]]*ai-generation:)' "$body_file"; then
  echo "Body already contains a generation footer" >&2
  exit 2
fi

case "$model_id" in
  gpt-5.6-sol) display_model="GPT-5.6 Sol" ;;
  gpt-5.6-terra) display_model="GPT-5.6 Terra" ;;
  gpt-5.6-luna) display_model="GPT-5.6 Luna" ;;
  sonnet-5) display_model="Claude Sonnet 5" ;;
  opus-5) display_model="Claude Opus 5" ;;
  opencode-go/glm-5.2) display_model="GLM 5.2" ;;
  opencode-go/glm-5.1) display_model="GLM 5.1" ;;
  opencode-go/kimi-k2.6) display_model="Kimi K2.6" ;;
  opencode-go/kimi-k2.7-code) display_model="Kimi K2.7 Code" ;;
  opencode-go/qwen3.7-max) display_model="Qwen 3.7 Max" ;;
  opencode-go/qwen3.7-plus) display_model="Qwen 3.7 Plus" ;;
  opencode-go/minimax-m3) display_model="MiniMax M3" ;;
  opencode-go/deepseek-v4-pro) display_model="DeepSeek V4 Pro" ;;
  opencode-go/deepseek-v4-flash) display_model="DeepSeek V4 Flash" ;;
  *) display_model="$model_id" ;;
esac

case "$control" in
  model_reasoning_effort) display_control="reasoning effort" ;;
  effort) display_control="effort" ;;
  thinking) display_control="thinking" ;;
  *) display_control="$control" ;;
esac

normalized_value="$(printf '%s' "$value" | tr '[:upper:]' '[:lower:]')"
case "$normalized_value" in
  default|unknown|unspecified|unset) visible_setting="" ;;
  *) visible_setting=" · ${display_control}: ${value}" ;;
esac

body="$(cat "$body_file")"
printf '%s\n\n<sub>Generated by %s%s.</sub>\n' "$body" "$display_model" "$visible_setting"
printf '<!-- ai-generation: model=%s; control=%s; value=%s -->\n' "$model_id" "$control" "$value"
